Use correct Append method
Once -Werror=format-security was turned on, the compiler correctly
identifies that this test method is using the wrong append function from
CStringStatic.

../libgpos/server/src/unittest/gpos/io/CFileTest.cpp:285:34: error: format not a string literal and no format arguments [-Werror=format-security]
  strTmpFile.AppendFormat(szTmpDir);

Technically, the compiler only flagged the first instance
  strTmpFile.AppendFormat(szTmpDir)

because the second instance
  strTmpFile.AppendBuffer(szFile)
is using a string literal. However, it seems like it would make more
sense to use AppendBuffer here since there are no format arguments.

Co-authored-by: Jesse Zhang <sbjesse@gmail.com>